### ISSUE TITLE
Confirmed working with Meian ST-VGT

### ISSUE THREAD

**Issue by eogmau** [RyuzakiKK/pyialarm#1]
Hi mate, looked through the code and could see the same parameters as another panel [Meian ST-VGT](https://www.amazon.com/PE-Meian-Intelligent-Business-Security-Magnetism/dp/B07BGXGG99). Have tried it in home-assistant and it works. Can you add please to the home assistant documentation on iAlarm  that it work with that alarm panel also. Thanks for your work.

**Comment by RyuzakiKK** [comment]
Thank you for this information.

As soon as I have some free time I'll check what's the best way to document it in home assistant.

**Comment by RyuzakiKK** [comment]
Meian is now mentioned in the iAlarm documentation on HA.
