### ISSUE TITLE
integrazione Antifurto365 allarme

### ISSUE THREAD

**Issue by PILLONA75** [RyuzakiKK/pyialarm#10]
Buongiorno,
sono nuovissimo di Home Assistant,sto cercando di capire come configurare la centralina iALLARM di ANTIFURTO365 che ormai ho già da 2 anni e mi trovo benissimo
Ho chiesto alla ditta se la centralina fosse compatibile con Home Assistant,mi hanno mandato un email con la procedura ma non capisco tantissimo,
ho capito che devo creare una cartella custom component su Assistant,e questo l'ho fatto, ho caricato tutti i file che mi hanno inviato tramite l'integrazione SAMBA nella cartella.
Non ho la più pallida idea come aggiungere la configurazione "ialarmxr nel configuration.yaml, non so se devo seguire della sintassi già pronta preformata da prendere da qualche parte e incollare nel configuration yaml.
Ho trovato l'integrazione IaLLARM nell'elenco integrazioni e presumo che debba configurarlo come ultimo passaggio dopo che ho fatto i precedenti.
Allego quello che mi ha scritto la ditta 
Qualcuno può aiutarmi nel risolvere il problema? anche un indicazione  di dove può esserci un tutorial ho un esempio di guida.

Grazie

1. Scarica il file allegato a questa email
3. Estrai tutti i files e copiali dentro alla tua cartella Home Assistant custom_components, ad esempio: /root/config/custom_components/ialarmxr3. 
2. Riavvia Home Assistant4. 
4. Aggiungi alla tua configuration.yaml di Home-Assistant la configurazione: "ialarmxr:"
5.  Riavvia di nuovo Home Assistant e attendere circa 5 minuti che l'integrazione venga installata
6. 6. Aggiungi la nuova integrazione ialarmxr dal menù integrazioni
7. 7. Configura la nuova integrazione

**Comment by RyuzakiKK** [comment]
> Ho trovato l'integrazione IaLLARM nell'elenco integrazioni e presumo che debba configurarlo come ultimo passaggio dopo che ho fatto i precedenti.

L'integrazione iAlarm che trovi nei [repository di Home Assistant](https://www.home-assistant.io/integrations/ialarm/) è solo per le vecchie centraline di iAlarm, non supporta le nuove iAlarm-XR, e tale integrazione fu realizzata dalla community, non da Antifurto365.

Nel tuo caso invece, devi usare l'integrazione custom che Antifurto365 ti ha fornito. Non so perché non l'abbiano aggiunta ad Home Assistant ufficialmente e invece necessita ancora di essere inserirla manualmente. Comunque, se hai dubbi su come configurarla, gli unici che possono aiutarti è il supporto di Antifurto365.

**Comment by PILLONA75** [comment]
grazie,  ho solo problemi nella configuration yaml,solo per la sintassi e le parole da scrivere,non penso che basti solo scrivere iALLARM
