### ISSUE TITLE
ialarm: Error on device update!

### ISSUE THREAD

**Issue by alexperrucci** [RyuzakiKK/pyialarm#3]
Hi RyuzakiKK,
first of all I would like to thank you for having create this library.
I have an iAlarm antifurtocasa365 an I'm trying to interact with it in Hassio (HassOS 2.12) to do some automations when alarm trigger. 
I did the configuration in the configutration.yaml file but when I start my hassio this error appear:

> ialarm: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 448, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/ialarm/alarm_control_panel.py", line 96, in update
    status = self._client.get_status()
  File "/usr/local/lib/python3.7/site-packages/pyialarm/pyialarm.py", line 43, in get_status
    if self.is_triggered(tree):
  File "/usr/local/lib/python3.7/site-packages/pyialarm/pyialarm.py", line 74, in is_triggered
    for line in script.text.split('\n'):
AttributeError: 'NoneType' object has no attribute 'text'
> 
The host, the username and password seems to be correct. If I try to connect direcley to the page RemoteCtr.htm I can see the alarm web panel:

![image](https://user-images.githubusercontent.com/44902794/71036820-b3f2f100-211e-11ea-8e27-d469c281648a.png)

Can you please help me to find out the reason?

Thanks in advance!
Alessandro

**Comment by RyuzakiKK** [comment]
If in you go to the page `/RemoteCtr.htm` with your browser (like in your screenshot) and you check the page source code, do you see an element `script` similar to this one?
```
<script type="text/javascript">
function WebOptStatusFct() 
{
    var s = "none";
```

From the error message the lib is failing to find the script from the html. So my guess is either your interface version is a bit different or it simply fails to load the page.

**Comment by alexperrucci** [comment]
Hi,
thanks for your quick response.
I'll check this evening and I'll let you know.

Have a good day
Alessandro

**Comment by alexperrucci** [comment]
Hi,
yes in the page source code I can see that snippet of code.
The strange think is that if I open the page "
http://192.168.1.81/RemoteCtr.htm" with IE 11 one out of 3 times it fails
to load or load the page partially.
With Chrome I have no problem...

What do you suggest me to do?

Thanks,
Alessandro

**Comment by RyuzakiKK** [comment]
Can you try this gist?
It's the same pyialarm but you can launch it directly without HA.
https://gist.github.com/RyuzakiKK/66c66587bbff2e1091e2da589379e832

Just change your password at line 93 and launch it with `python3 pyialarm.py `

If everything is fine you should see the webpage source code and a number for the current alarm status.

**Comment by RyuzakiKK** [comment]
The expected result should be something like this:
```
$ python3 pyialarm.py
[...]
</div>
</div><!-- End row -->
</div><!-- End container -->
</body>
</html>
END


3
```

Where the `3` means that the alarm is now in the `DISARMED` status.

**Comment by alexperrucci** [comment]
I'll check it this evening.

Thanks a lot!
Alessandro

**Comment by alexperrucci** [comment]
Hi,
Yesterday I did a test. I created a command line sensor with a call to your
script.
I added the sensor to my overview and when I opened it I correctly saw the
status number...

I dont know what could have been wrong with the other kind of operation.
At the moment for my needs it could be enough.

Maybe after Christmas holidays I'll try to do more checks.

Thank you very mutch for your help!
Have a nice Christmas and I wish you all the best for the ney year.
Alessandro

**Comment by RyuzakiKK** [comment]
@alexperrucci Good that at least that works! :)

Then I'm guessing that probably there is something wrong with the configuration of HA's yaml?

I suggest you to double check that everything is written correctly, and also you can try to wrap your pin with double quotes: `password: "012345"`

**Comment by alexperrucci** [comment]
Thanks! I'll try.

Alessandro

**Comment by RyuzakiKK** [comment]
Closing because now this library doesn't use webscraping anymore.
