### ISSUE TITLE
Home assistant

### ISSUE THREAD

**Issue by wifi75** [RyuzakiKK/pyialarm#4]
Hello, How I can Install on HA?

**Comment by RyuzakiKK** [comment]
I'm trying to reintroduce the iAlarm integration in HA. You can check the progress here https://github.com/home-assistant/core/pull/43525

By the end of this week I should be able to create a new revision that implements the required changes.

**Comment by wifi75** [comment]
great news, do you make sure that it can then be downloaded directly from Hacs?

**Comment by RyuzakiKK** [comment]
It will be included as a "native" integration. Not a community external integration that requires HACS.

**Comment by wifi75** [comment]
hello @RyuzakiKK your project it'is ready for HA?

**Comment by RyuzakiKK** [comment]
I'm waiting for a review https://github.com/home-assistant/core/pull/43525

**Comment by wifi75** [comment]
hello @RyuzakiKK any new ?

**Comment by RyuzakiKK** [comment]
No, still waiting for a review.

**Comment by RyuzakiKK** [comment]
@wifi75 FYI the pull request on HA has been approved and it will likely be included since the next HA 2021.5

**Comment by RyuzakiKK** [comment]
Available in HA 2021.5.0
