### ISSUE TITLE
Mod get_status function

### ISSUE THREAD

**Issue by piopalladino** [RyuzakiKK/pyialarm#5]
Ciao Ludovico,
sto seguendo il tuo lavoro da tempo, e ci siamo sentiti anche via mail...
Controllando la funzione get_status ho notato che attivi il TRIGGERD solo in base alle zone_status 

zone_status = self._send_request_list('/Root/Host/GetByWay', command)
        if zone_status is not None:
            for zone in zone_status:
                if zone & self.ZONE_ALARM:
                    return self.TRIGGERED

ma le zone rimangono in allarme anche quando l'antifurto e stato disabilitato se prima e scattato (memoria intervento)
Pertanto dovresti inserire un IF a monte che consideri alarm_status = ARMED_AWAY OR alarm_status = ARMED_STAY

**Comment by RyuzakiKK** [comment]
Ah si hai ragione, grazie. Appena ho un po di tempo faccio una prova sul mio antifurto per controllare che funzioni correttamente e poi implemento la modifica.

**Comment by piopalladino** [comment]
Grazie per la risposta...
Scusa ancora... ma l'appetito vien mangiando...
ho letto che riimplementerai l'integrazione con HA... grande...
Potresti aggiungere come attributi aggiuntivi anche le variabili **alarm_status** e **zone_status**... anche come semplice valore numerico, poi eventualmente con un template esterno estri i dati che ti servono... io per esempio sto monitorando lo stato dei vari sensori delle finestre con il ZONE_FAULT = (1 << 3)... quando è a 1 la finestra e aperta...

**Comment by wifi75** [comment]
@piopalladino how do you run this script?on ubuntu what should be installed?

**Comment by RyuzakiKK** [comment]
Adesso lo stato TRIGGERED non viene mostrato se l'allarme è stato disattivato.

È possibile aggiungere lo stato dei singoli sensori su HA. Purtroppo però richiede cambiamenti sia su questa libreria (probabilmente non troppo difficile) e anche sull'integrazione su HA (più complicato).
Il tempo che riesco a dedicare a questo progetto non è molto, quindi nel breve periodo non credo di essere in grado di implementarlo.

**Comment by piopalladino** [comment]
> Adesso lo stato TRIGGERED non viene mostrato se l'allarme è stato disattivato.
> 
> È possibile aggiungere lo stato dei singoli sensori su HA. Purtroppo però richiede cambiamenti sia su questa libreria (probabilmente non troppo difficile) e anche sull'integrazione su HA (più complicato).
> Il tempo che riesco a dedicare a questo progetto non è molto, quindi nel breve periodo non credo di essere in grado di implementarlo.

Grazie... ho visto... se vuoi ti posso dare una mano per l'implementazione su HA... adesso sto usando l'implementazione con node red... ma non mi piace perché utilizza lo scaping... se ti va di condividere la nuova implementazione di ialarm su HA.
Sto anche testando una arming a zone preimpostate (per esempio solo sensori zona garage) prima del comando di arm....

Garazie ancora e buonaserata
