### ISSUE TITLE
365 alarm system compatibility (ialarm XR)

### ISSUE THREAD

**Issue by SmartM-ui** [RyuzakiKK/pyialarm#6]
Hi,
I was looking forward to your integration, as my 365 alarm system unit (ialarm XR5), having no WEB access panel, I have never managed to integrate it into Home Assistant.
Unfortunately, even with your new integration, my control unit continues to be incompatible and the integration procedure stops already at the first step of entering the host (IP address).
Would it be possible to include integration for the relatively new anti-theft control units 365 (ialarm XR)?
Thank you

**Comment by RyuzakiKK** [comment]
This library uses the same APIs as the Android application "Guard IP". But apparently newer ialarm systems require a new app called "iAlarm XR".
If you say that this library doesn't work on your system, probably means that they changed the API, and given the complete lack of security in this older API, I suspect that they wrote a new one from the ground up.

**Comment by SmartM-ui** [comment]
Hi,
thanks for replying.
To work, the new control units, require the iAlarmXR app.  They have implemented the IFTTT service, but it has about an hour delay in  HA, practically the service is unusable.  
If you want, I am available to carry out tests.  
Good day

**Comment by bigmoby** [comment]
I guys, if you want I'm available too. Feel free to contact me for tests 👍

**Comment by RyuzakiKK** [comment]
@SmartM-ui or @bigmoby can one of you please try this one? https://raw.githubusercontent.com/RyuzakiKK/pyialarm/test_ialarm_xr/pyialarm/pyialarm.py

Just download the file, replace `IAlarm("YOUR_IP_HERE")` (its at the end of the file) with your alarm ip address, e.g. `IAlarm("192.168.10.10")`, then run it with `python3 pyialarm.py` and report back the output.

I simply added a few debug prints to understand what the alarm replies. If we are very lucky it might be something just slightly different, but I wouldn't hold my breath. Probably it is a completely different API.

**Comment by bigmoby** [comment]
Hi @RyuzakiKK ,
this is my response:

<img width="892" alt="Screenshot 2021-05-10 at 16 16 35" src="https://user-images.githubusercontent.com/11453002/117673548-2bf60700-b1ab-11eb-8301-26a41a8f7f83.png">

**Comment by SmartM-ui** [comment]
> @SmartM-ui or @bigmoby can one of you please try this one? https://raw.githubusercontent.com/RyuzakiKK/pyialarm/test_ialarm_xr/pyialarm/pyialarm.py
> 
> Just download the file, replace `IAlarm("YOUR_IP_HERE")` (its at the end of the file) with your alarm ip address, e.g. `IAlarm("192.168.10.10")`, then run it with `python3 pyialarm.py` and report back the output.
> 
> I simply added a few debug prints to understand what the alarm replies. If we are very lucky it might be something just slightly different, but I wouldn't hold my breath. Probably it is a completely different API.

Thanks, I try

**Comment by SmartM-ui** [comment]
Hi @RyuzakiKK ,
this is my screen

<img width="478" alt="Schermata 2021-05-10 alle 16 27 58" src="https://user-images.githubusercontent.com/63554131/117675381-cc006000-b1ac-11eb-8926-f4dbdfd832b8.png">

**Comment by RyuzakiKK** [comment]
The timeout waiting for a reply means that the alarm didn't understand the request we sent. Probably the encode method is different, but that's just a guess.

Unfortunately I can't volunteer myself to analyze the new android app to understand how the new API works. The best I can do for now is just add a note in HA documentation stating that the newer iAlarm XR is not supported.

**Comment by RyuzakiKK** [comment]
@SmartM-ui You are missing the `dicttoxml` python library. But It's very likely that your output will be similar to the one @bigmoby  posted, so there is no need to retry.

**Comment by SmartM-ui** [comment]
> @SmartM-ui You are missing the `dicttoxml` python library. But It's very likely that your output will be similar to the one @bigmoby posted, so there is no need to retry.

OK, Thanks

**Comment by bigmoby** [comment]
@SmartM-ui you could solve with `pip3 install dicttoxml` and after that `pip3 install xmltodict` (I suppose also this library is missing) 👍

**Comment by bigmoby** [comment]
Yes, I suppose something changed, ID is negotiated at the beginning of the service, something like that:

```
package com.test;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants;
import javax.xml.xpath.XPathExpressionException;
import javax.xml.xpath.XPathFactory;
import java.util.Arrays;

public class Fabio {
    public static void main(String[] args) {
        byte[] pushRegister = Fabio.pushRegister("[THE IALARM ID]");
        blablabla...
    }

    public static Document getDocument() {
        DocumentBuilder documentBuilder;
        try {
            documentBuilder = DocumentBuilderFactory.newInstance().newDocumentBuilder();
        } catch (ParserConfigurationException e) {
            e.printStackTrace();
            documentBuilder = null;
        }
        return documentBuilder.newDocument();
    }

    public static void setXmlNodeValue(Document document, String str, String str2) {
        Element element;
        String[] split = str.split("/");
        Element documentElement = document.getDocumentElement();
        XPath newXPath = XPathFactory.newInstance().newXPath();
        String str3 = "/";
        Element element2 = documentElement;
        for (int i = 1; i < split.length; i++) {
            str3 = str3 + "/" + split[i];
            try {
                element = (Element) newXPath.evaluate(str3, document, XPathConstants.NODE);
                if (element == null) {
                    element = document.createElement(split[i]);
                    if (i + 1 == split.length) {
                        element.appendChild(document.createTextNode(str2));
                    }
                    if (i == 1) {
                        document.appendChild(element);
                    } else {
                        element2.appendChild(element);
                    }
                }
            } catch (XPathExpressionException unused) {
                element = document.createElement(split[i]);
                element2.appendChild(element);
            }
            element2 = element;
        }
    }

    public static void setXmlNodeEmpty(Document document, String str) {
        Element element;
        String[] split = str.split("/");
        Element documentElement = document.getDocumentElement();
        XPath newXPath = XPathFactory.newInstance().newXPath();
        String str2 = "/";
        Element element2 = documentElement;
        for (int i = 1; i < split.length; i++) {
            str2 = str2 + "/" + split[i];
            try {
                element = (Element) newXPath.evaluate(str2, document, XPathConstants.NODE);
                if (element == null) {
                    element = document.createElement(split[i]);
                    if (i == 1) {
                        document.appendChild(element);
                    } else {
                        element2.appendChild(element);
                    }
                }
            } catch (XPathExpressionException unused) {
                element = document.createElement(split[i]);
                element2.appendChild(element);
            }
            element2 = element;
        }
    }

    public static String getXml(DOMSource dOMSource) {
        try {
            Properties properties = new Properties();
            properties.setProperty("omit-xml-declaration", "yes");
            Transformer newTransformer = TransformerFactory.newInstance().newTransformer();
            newTransformer.setOutputProperties(properties);
            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
            newTransformer.transform(dOMSource, new StreamResult(byteArrayOutputStream));
            String obj = byteArrayOutputStream.toString();
            String format = String.format("%04d", new Object[]{Integer.valueOf(1)}); // at moment removed
            String format2 = String.format("%04d", new Object[]{Integer.valueOf(obj.toString().length())});
            return "@ieM" + format2 + format + "0000" + "" + obj.toString() + format;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public static byte[] pushRegister(String str) {
        try {
            Document document = getDocument();
            setXmlNodeValue(document, "/Root/Pair/Push/Id", "STR," + str.getBytes().length + "|" + str);
            setXmlNodeEmpty(document, "/Root/Pair/Push/Err");
            return getXml(new DOMSource(document.getDocumentElement())).getBytes("UTF8");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
            return null;
        }
    }
}```

**Comment by SmartM-ui** [comment]
> @SmartM-ui you could solve with `pip3 install dicttoxml` and after that `pip3 install xmltodict` (I suppose also this library is missing) 👍

Thank you

**Comment by SmartM-ui** [comment]
Thanks @bigmoby , I installed the two missing components and this is the result of the .py

@RyuzakiKK Thanks for opening the request, if this other one can be useful too, I'll try 

<img width="591" alt="Schermata 2021-05-10 alle 19 36 57" src="https://user-images.githubusercontent.com/63554131/117701474-9321b480-b1c7-11eb-84f2-676d17a9a9db.png">

**Comment by bigmoby** [comment]
> The timeout waiting for a reply means that the alarm didn't understand the request we sent. Probably the encode method is different, but that's just a guess.
> 
> Unfortunately I can't volunteer myself to analyze the new android app to understand how the new API works. The best I can do for now is just add a note in HA documentation stating that the newer iAlarm XR is not supported.

Hi @RyuzakiKK ,
the IP address, I suppose, should be the host shown in the mobile app and not the IP address of the alarm itself.

**Comment by SmartM-ui** [comment]
> > The timeout waiting for a reply means that the alarm didn't understand the request we sent. Probably the encode method is different, but that's just a guess.
> > Unfortunately I can't volunteer myself to analyze the new android app to understand how the new API works. The best I can do for now is just add a note in HA documentation stating that the newer iAlarm XR is not supported.
> 
> Hi @RyuzakiKK ,
> the IP address, I suppose, should be the host shown in the mobile app and not the IP address of the alarm itself.

I checked and port 18034 refers to the external IP address and not the local network one.  In fact, in the same tab, the username and password always refer to the external IP

**Comment by RyuzakiKK** [comment]
> > The timeout waiting for a reply means that the alarm didn't understand the request we sent. Probably the encode method is different, but that's just a guess.
> > Unfortunately I can't volunteer myself to analyze the new android app to understand how the new API works. The best I can do for now is just add a note in HA documentation stating that the newer iAlarm XR is not supported.
> 
> Hi @RyuzakiKK ,
> the IP address, I suppose, should be the host shown in the mobile app and not the IP address of the alarm itself.

What's the host in the mobile app? Your external IP address?

**Comment by RyuzakiKK** [comment]
> > > The timeout waiting for a reply means that the alarm didn't understand the request we sent. Probably the encode method is different, but that's just a guess.
> > > Unfortunately I can't volunteer myself to analyze the new android app to understand how the new API works. The best I can do for now is just add a note in HA documentation stating that the newer iAlarm XR is not supported.
> > 
> > 
> > Hi @RyuzakiKK ,
> > the IP address, I suppose, should be the host shown in the mobile app and not the IP address of the alarm itself.
> 
> I checked and port 18034 refers to the external IP address and not the local network one. In fact, in the same tab, the username and password always refer to the external IP

Yes, because I guess that the alarm by default asks to open the port 18034 to the external with upnp. In this way you could use their app even if you are not at home. But when in LAN you should be able to communicate directly to the alarm with local messages.
E.g. If you use nmap (`nmap -p 18034 local_ip_of_alarm`) you should be able to confirm that this port is indeed open.

If you are in the same LAN, it shouldn't make sense to try to use your external IP for a direct connection to another device that is in the same network.

**Comment by SmartM-ui** [comment]
> > > > The timeout waiting for a reply means that the alarm didn't understand the request we sent. Probably the encode method is different, but that's just a guess.
> > > > Unfortunately I can't volunteer myself to analyze the new android app to understand how the new API works. The best I can do for now is just add a note in HA documentation stating that the newer iAlarm XR is not supported.
> > > 
> > > 
> > > Hi @RyuzakiKK ,
> > > the IP address, I suppose, should be the host shown in the mobile app and not the IP address of the alarm itself.
> > 
> > 
> > I checked and port 18034 refers to the external IP address and not the local network one. In fact, in the same tab, the username and password always refer to the external IP
> 
> Yes, because I guess that the alarm by default asks to open the port 18034 to the external with upnp. In this way you could use their app even if you are not at home. But when in LAN you should be able to communicate directly to the alarm with local messages.
> E.g. If you use nmap (`nmap -p 18034 local_ip_of_alarm`) you should be able to confirm that this port is indeed open.
> 
> If you are in the same LAN, it shouldn't make sense to try to use your external IP for a direct connection to another device that is in the same network.

Yes, host up

![Screenshot_20210510-223658_Home Assistant](https://user-images.githubusercontent.com/63554131/117723913-4fd53f00-b1e3-11eb-9b8c-1f1dcccfbc9b.jpg)

**Comment by bigmoby** [comment]
> > > The timeout waiting for a reply means that the alarm didn't understand the request we sent. Probably the encode method is different, but that's just a guess.
> > > Unfortunately I can't volunteer myself to analyze the new android app to understand how the new API works. The best I can do for now is just add a note in HA documentation stating that the newer iAlarm XR is not supported.
> > 
> > Hi @RyuzakiKK ,
> > the IP address, I suppose, should be the host shown in the mobile app and not the IP address of the alarm itself.
> 
> What's the host in the mobile app? Your external IP address?

Hi @RyuzakiKK 
Probably you got right but the APK tries to connect to a different IP that is not the external IP. Could be a host service owned by Antifurto365 that creates a tunnel access to the alarm?!

**Comment by bigmoby** [comment]
Hi @RyuzakiKK ,
thank you so much for your great library 🙏
In my spare time I did some reverse engineering for the iAlarmXR protocol and I forked and modified you library.
Please if you want take a look at https://github.com/bigmoby/pyialarmxr

**Comment by RyuzakiKK** [comment]
@bigmoby Well done!
Do you think it would be worth it/feasible for you to create a PR to implement the XR support in `pyialarm` to have a single lib that support both?

Of course there must be a way to automatically detect the alarm type either at runtime or, if it's not possible, with launch parameter like the current host and port.

**Comment by bigmoby** [comment]
Hi @RyuzakiKK 
Mmm...I'm not (yet) aware of https://github.com/home-assistant/core/tree/dev/homeassistant/components/ialarm implementation and home assistant component in general 🤔 ...but I think should be possible with a flag parameter on startup. The two alarm systems differ in a different authentication routine but the others API are quite the same. 
I found a weird issue in  empty xml tags: for example `<Err></Err>` throws an error in the communication protocol...so, I reimplemented with lxml library supporting `</Err>` compact empty tags style.

**Comment by bigmoby** [comment]
Hi @RyuzakiKK ,
I analyzed your iAlarm component integration but I haven't found an elegant way to integrate both implementation in the same. I don't know how to select, and then configure, the component: I only imagine to create the same configuration dialog but, for GuardIP system, username and password fields could appear misleading entries! In the backend I could select a ialarm or ialarmxr instance if all the fields have been filled...Mmm...not elegant at all! 🤨
So I create this PR https://github.com/home-assistant/core/pull/67817 please if you want take a look on this 🙏
I really appreciate it!

**Comment by SmartM-ui** [comment]
> Hi @RyuzakiKK , thank you so much for your great library 🙏 In my spare time I did some reverse engineering for the iAlarmXR protocol and I forked and modified you library. Please if you want take a look at https://github.com/bigmoby/pyialarmxr

hi @bigmoby,
if I can be of help with some tests, I have the XR5.  
If you can, tell me the procedure.  
Thank you

**Comment by bigmoby** [comment]
> hi @bigmoby, if I can be of help with some tests, I have the XR5. If you can, tell me the procedure. Thank you

Hi @SmartM-ui ,
thank you for your help, the tests are ok, if you want review the code please feel free to contribute 👍
If you want test it in local please checkout the PR branch and run in local environment (I suggest you VSCode...Dev container already configured to run on this)
Cheers 👍

**Comment by bigmoby** [comment]
HI @RyuzakiKK please could you review my PR https://github.com/home-assistant/core/pull/67817 ? 
I would really appreciate it 🙏

**Comment by RyuzakiKK** [comment]
@bigmoby Okay. As soon as I have some free time I'll try to review your PR.

**Comment by bigmoby** [comment]
> @bigmoby Okay. As soon as I have some free time I'll try to review your PR.

Thanks a lot! 🙏
Really really appreciate it!

**Comment by RyuzakiKK** [comment]
The integration for HA has just been merged, so it will be included in the next HA release.
Congratulations @bigmoby.

Now that is all set, I'm closing this issue now. To discuss ialarm XR development you can probably use https://github.com/bigmoby/pyialarmxr/issues

**Comment by bigmoby** [comment]
> The integration for HA has just been merged, so it will be included in the next HA release. Congratulations @bigmoby.
> 
> Now that is all set, I'm closing this issue now. To discuss ialarm XR development you can probably use https://github.com/bigmoby/pyialarmxr/issues

Thanks a lot @RyuzakiKK I appreciate your contribution and your suggestions very much! Thanks a lot 🙏
